"""add_user_id_to_pets_table

Revision ID: 21ab63d1e995
Revises: e730944c95b8
Create Date: 2025-08-15 21:25:07.209309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21ab63d1e995'
down_revision = 'e730944c95b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('pets', 'photo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('photo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pets', type_='foreignkey')
    op.drop_column('pets', 'user_id')
    # ### end Alembic commands ### 