"""Ensure User model matches frontend requirements

Revision ID: 600272fb10be
Revises: 7c0242749bf2
Create Date: 2025-07-23 16:58:22.564362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600272fb10be'
down_revision = '7c0242749bf2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 