"""add barangay and picture_url to meat inspection

Revision ID: a43da4c138ef
Revises: e2247104a05b
Create Date: 2025-11-04 23:12:04.685955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a43da4c138ef'
down_revision = 'e2247104a05b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meat_inspection_records', sa.Column('barangay', sa.String(length=255), nullable=True))
    op.add_column('meat_inspection_records', sa.Column('picture_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meat_inspection_records', 'picture_url')
    op.drop_column('meat_inspection_records', 'barangay')
    # ### end Alembic commands ### 