"""add_admin_id_to_reports_and_alerts

Revision ID: bcfdfb9f949e
Revises: c5ed4baeff16
Create Date: 2025-08-17 16:12:05.059954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcfdfb9f949e'
down_revision = 'c5ed4baeff16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medical_records', 'procedures_done',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('medical_records', 'findings',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('medical_records', 'recommendations',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('medical_records', 'vaccine_used',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=True)
    op.create_foreign_key(None, 'medical_records', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medical_records', type_='foreignkey')
    op.alter_column('medical_records', 'vaccine_used',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('medical_records', 'recommendations',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('medical_records', 'findings',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('medical_records', 'procedures_done',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ### 