"""add_pet_relationship_to_medical_records

Revision ID: c5ed4baeff16
Revises: ef5476b0f0c0
Create Date: 2025-08-17 14:41:39.494363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5ed4baeff16'
down_revision = 'ef5476b0f0c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('date_of_visit', sa.Date(), nullable=False))
    op.add_column('medical_records', sa.Column('next_visit', sa.Date(), nullable=True))
    op.add_column('medical_records', sa.Column('procedure_done', sa.Text(), nullable=False))
    op.add_column('medical_records', sa.Column('recommendation', sa.Text(), nullable=False))
    op.add_column('medical_records', sa.Column('vaccine_used_medication', sa.Text(), nullable=False))
    op.drop_column('medical_records', 'recommendations')
    op.drop_column('medical_records', 'user_id')
    op.drop_column('medical_records', 'veterinarian')
    op.drop_column('medical_records', 'procedures_done')
    op.drop_column('medical_records', 'date_of_next_visit')
    op.drop_column('medical_records', 'notes')
    op.drop_column('medical_records', 'medications')
    op.drop_column('medical_records', 'vaccine_used')
    op.drop_column('medical_records', 'date_visited')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('date_visited', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('medical_records', sa.Column('vaccine_used', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('medical_records', sa.Column('medications', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('medical_records', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('medical_records', sa.Column('date_of_next_visit', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('medical_records', sa.Column('procedures_done', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('medical_records', sa.Column('veterinarian', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('medical_records', sa.Column('user_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.add_column('medical_records', sa.Column('recommendations', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('medical_records', 'vaccine_used_medication')
    op.drop_column('medical_records', 'recommendation')
    op.drop_column('medical_records', 'procedure_done')
    op.drop_column('medical_records', 'next_visit')
    op.drop_column('medical_records', 'date_of_visit')
    # ### end Alembic commands ### 