"""add post_abattoir_records

Revision ID: e2247104a05b
Revises: bfb9fa343bac
Create Date: 2025-11-04 22:29:51.653871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2247104a05b'
down_revision = 'bfb9fa343bac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_abattoir_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.String(length=10), nullable=False),
    sa.Column('barangay', sa.String(length=255), nullable=False),
    sa.Column('establishment', sa.String(length=255), nullable=False),
    sa.Column('doc_mic', sa.Boolean(), nullable=False),
    sa.Column('doc_vhc', sa.Boolean(), nullable=False),
    sa.Column('doc_sp', sa.Boolean(), nullable=False),
    sa.Column('color_ok', sa.Boolean(), nullable=False),
    sa.Column('texture_ok', sa.Boolean(), nullable=False),
    sa.Column('odor_ok', sa.Boolean(), nullable=False),
    sa.Column('condem', sa.Boolean(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_abattoir_records_id'), 'post_abattoir_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_abattoir_records_id'), table_name='post_abattoir_records')
    op.drop_table('post_abattoir_records')
    # ### end Alembic commands ### 