"""add_species_gender_to_animal_control_records

Revision ID: ebeae5e51ec8
Revises: 911f6d4360de
Create Date: 2025-07-29 17:47:20.414517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebeae5e51ec8'
down_revision = '911f6d4360de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal_control_records', sa.Column('species', sa.String(length=50), nullable=True))
    op.add_column('animal_control_records', sa.Column('gender', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animal_control_records', 'gender')
    op.drop_column('animal_control_records', 'species')
    # ### end Alembic commands ### 