"""add_cascade_delete_to_user_foreign_keys

Revision ID: ef5476b0f0c0
Revises: 21ab63d1e995
Create Date: 2025-08-15 21:28:56.910236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef5476b0f0c0'
down_revision = '21ab63d1e995'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('appointments_user_id_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('pain_assessments_user_id_fkey'), 'pain_assessments', type_='foreignkey')
    op.create_foreign_key(None, 'pain_assessments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('vaccination_records_user_id_fkey'), 'vaccination_records', type_='foreignkey')
    op.create_foreign_key(None, 'vaccination_records', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vaccination_records', type_='foreignkey')
    op.create_foreign_key(op.f('vaccination_records_user_id_fkey'), 'vaccination_records', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'pain_assessments', type_='foreignkey')
    op.create_foreign_key(op.f('pain_assessments_user_id_fkey'), 'pain_assessments', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_user_id_fkey'), 'appointments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ### 